log = "info,monitor=debug"

execution_http_url = "http://1.geth.mainnet.ethnodes.brainbot.com:8545/"
execution_ws_url = "ws://1.geth.mainnet.ethnodes.brainbot.com:8546/"
consensus_http_url = "http://1.geth.mainnet.ethnodes.brainbot.com:5052/"

db_enabled = true
db_connection = "postgres://postgres@localhost:5432/monitor"
